### ISSUE TITLE
ros-cli loads AWS environment variables which might conflict with local settings

### ISSUE THREAD

**Issue by rpbaltazar** [rails-on-services/ros-cli#124]
running ros-native sets the AWS environment variables as they are expected to be set for services that depend on AWS to run.

When running `ros be sh <service name>` it tries to fetch the AWS caller identity, but because there are env variables set, tries to use those instead. For development this leads to using localstack configuration which is invalid.

I have to unset the AWS keys before i can run any ros-cli commands to run on the kluster.
I think this is a bug

**Comment by peterhoeg** [comment]
>   I think this is a bug

This might be used for CI. Needs to be investigated.

**Comment by rpbaltazar** [comment]
@peterhoeg this has been solved, right? I believe from our discussion this morning this is no longer an issue.

**Comment by peterhoeg** [comment]
Correct, we no longer load `platform.env` into the shell.
